// =============================================================================
// relationships-data.js  --  Input/Output Map diagram data (no React)
// =============================================================================

export const REL_COLORS = {
  fixed:      { bg:"#1e293b", border:"#64748b", text:"#94a3b8", label:"LOCKED IN" },
  inflated:   { bg:"#1e3a5f", border:"#3b82f6", text:"#60a5fa", label:"FIXED+INFLATION" },
  choice:     { bg:"#3b2a00", border:"#f59e0b", text:"#fbbf24", label:"YOUR DECISIONS" },
  market:     { bg:"#2d1b4e", border:"#a855f7", text:"#c084fc", label:"MARKET ASSUMPTION" },
  endogenous: { bg:"#0f2d1f", border:"#34d399", text:"#6ee7b7", label:"COMPUTED" },
  output:     { bg:"#2d1a1a", border:"#f87171", text:"#fca5a5", label:"KEY OUTPUT" },
};
export const RNODES = [
  // Col 0 -- Fixed / income
  { id:"pension",      label:"Pension",               sub:"$3,300/mo",             type:"fixed",      col:0, row:0 },
  { id:"yourSs",       label:"Your SS",               sub:"$3,271-$3,874/mo",      type:"fixed",      col:0, row:1 },
  { id:"brendaSs",     label:"Brenda SS",             sub:"$1,937/mo spousal",     type:"fixed",      col:0, row:2 },
  { id:"workIncome",   label:"Work Income",           sub:"curve: drag to shape income path",    type:"choice",     col:0, row:3 },
  { id:"hiDebtInit",   label:"HI Debt",               sub:"$306K @ 8-14%",         type:"fixed",      col:0, row:4 },
  { id:"ssAge",        label:"SS Start Age",          sub:"65-70 choice",          type:"choice",     col:0, row:5 },
  // Col 1 -- Property
  { id:"sixthSt",      label:"6th St: Keep/Sell/Rent",sub:"$1.7M / $806K mtg",    type:"choice",     col:1, row:0 },
  { id:"sixthRental",  label:"6th St Rental Mode",   sub:"MTR/LTR if vacated",    type:"choice",     col:1, row:1 },
  { id:"duplexProp",   label:"15th St Duplex",        sub:"$1.5M / $348K mtg",     type:"fixed",      col:1, row:2 },
  { id:"fifthTopMode", label:"15th Top: STR/LTR/MTR", sub:"Top unit mode",         type:"choice",     col:1, row:3 },
  { id:"strRate",      label:"15th Top Rate",         sub:"$1,400-$4,200/mo",      type:"choice",     col:1, row:4 },
  { id:"lafProp",      label:"Lafayette",             sub:"$590K / $181K mtg",     type:"fixed",      col:1, row:5 },
  { id:"rentalGrowth", label:"Rent Growth",           sub:"1.5-4.5%/yr",           type:"market",     col:1, row:6 },
  { id:"reApp",        label:"RE Appreciation",       sub:"2-6%/yr",               type:"market",     col:1, row:7 },
  // Col 2 -- Costs
  { id:"healthCosts",  label:"Health Insurance",      sub:"$2,092->$759/mo",       type:"inflated",   col:2, row:0 },
  { id:"propCosts",    label:"Prop Tax + Ins",        sub:"$2,377/mo, 3.5%/yr",    type:"inflated",   col:2, row:1 },
  { id:"coreLiving",   label:"Core Living",           sub:"$2,650/mo, 2.8%/yr",    type:"inflated",   col:2, row:2 },
  { id:"mortgageIO",   label:"Mortgage IO Pmts",      sub:"$5,499/mo today",       type:"fixed",      col:2, row:3 },
  { id:"mortgagePnI",  label:"Mortgage Full P&I",     sub:"+$2,891/mo at switch",  type:"endogenous", col:2, row:4 },
  { id:"hiMinimums",   label:"HI Debt Minimums",      sub:"$3,724/mo",             type:"fixed",      col:2, row:5 },
  { id:"maintenance",  label:"Maintenance",           sub:"% of structure (CF tab)", type:"endogenous", col:2, row:6 },
  { id:"famLoan",      label:"Family Loan",           sub:"$25K, 8mo priority",    type:"choice",     col:2, row:7 },
  { id:"diCap",        label:"DI Cap (derived)",      sub:"disc + RD + OB top-ups",type:"endogenous", col:2, row:8 },
  // Col 3 -- Computed
  { id:"rentalIncome", label:"Rental Income",         sub:"$8,670+/mo total",      type:"endogenous", col:3, row:0 },
  { id:"totalIncome",  label:"Total Income",          sub:"passive + work",        type:"endogenous", col:3, row:2 },
  { id:"totalCosts",   label:"Total Costs",           sub:"all obligations",       type:"endogenous", col:3, row:4 },
  { id:"debtSweep",    label:"Debt Sweep",            sub:"FCF minus DI cap",       type:"endogenous", col:3, row:5 },
  { id:"hiClearDate",  label:"HI Debt Clears",        sub:"~2033 (estimated)",   type:"endogenous", col:3, row:6 },
  { id:"ioConvert",    label:"IO -> P&I Convert",     sub:"same yr as clear",      type:"endogenous", col:3, row:7 },
  { id:"investedCash", label:"Invested Cash",         sub:"SB: ~$880K @ 5.5%",     type:"endogenous", col:3, row:8 },
  // Col 4 -- Outputs
  { id:"reqWork",      label:"Work Income Req'd",     sub:"months until zero",     type:"output",     col:4, row:1 },
  { id:"dispIncome",   label:"Free Cash Flow",     sub:"after all costs",       type:"output",     col:4, row:3 },
  { id:"netWorth",     label:"Net Worth",             sub:"properties minus debt", type:"output",     col:4, row:5 },
  { id:"hiDebtBal",    label:"HI Debt Balance",       sub:"paydown trajectory",    type:"output",     col:4, row:6 },
  { id:"workFreeDate", label:"Work-Free Date",        sub:"passive > all costs",   type:"output",     col:4, row:7 },
];
export const REDGES = [
  { f:"pension",      t:"totalIncome",  s:3 },
  { f:"yourSs",       t:"totalIncome",  s:3 },
  { f:"brendaSs",     t:"totalIncome",  s:2 },
  { f:"workIncome",   t:"totalIncome",  s:2 },
  { f:"rentalIncome", t:"totalIncome",  s:3 },
  { f:"ssAge",        t:"yourSs",       s:3, lbl:"timing" },
  { f:"ssAge",        t:"reqWork",      s:2, lbl:"earlier = less work" },
  { f:"duplexProp",   t:"rentalIncome", s:3, lbl:"bottom always" },
  { f:"lafProp",      t:"rentalIncome", s:2 },
  { f:"sixthRental",  t:"rentalIncome", s:3, lbl:"if vacated" },
  { f:"fifthTopMode", t:"rentalIncome", s:3, lbl:"STR/LTR/MTR" },
  { f:"strRate",      t:"rentalIncome", s:2 },
  { f:"rentalGrowth", t:"rentalIncome", s:2 },
  { f:"sixthSt",      t:"sixthRental",  s:2, lbl:"if move to 15th" },
  { f:"sixthSt",      t:"investedCash", s:3, lbl:"SB: ~$880K" },
  { f:"sixthSt",      t:"propCosts",    s:2, lbl:"SA: +$1,073/mo" },
  { f:"sixthSt",      t:"mortgageIO",   s:3, lbl:"SA: +$3,273/mo IO" },
  { f:"sixthSt",      t:"netWorth",     s:3 },
  { f:"duplexProp",   t:"propCosts",    s:2 },
  { f:"lafProp",      t:"propCosts",    s:1 },
  { f:"duplexProp",   t:"mortgageIO",   s:3, lbl:"+$1,260/mo IO" },
  { f:"lafProp",      t:"mortgageIO",   s:2, lbl:"+$966/mo P&I" },
  { f:"maintenance",  t:"totalCosts",   s:2, lbl:"per-unit annual" },
  { f:"famLoan",      t:"totalCosts",   s:2, lbl:"8mo priority" },
  { f:"healthCosts",  t:"totalCosts",   s:2 },
  { f:"propCosts",    t:"totalCosts",   s:2 },
  { f:"coreLiving",   t:"totalCosts",   s:2 },
  { f:"mortgageIO",   t:"totalCosts",   s:3 },
  { f:"mortgagePnI",  t:"totalCosts",   s:3, lbl:"+$2,891/mo" },
  { f:"hiMinimums",   t:"totalCosts",   s:2 },
  { f:"totalIncome",  t:"debtSweep",    s:2 },
  { f:"totalCosts",   t:"debtSweep",    s:2 },
  { f:"diCap",        t:"debtSweep",    s:2, lbl:"surplus above cap" },
  { f:"debtSweep",    t:"hiDebtBal",    s:3, lbl:"attacks avalanche" },
  { f:"debtSweep",    t:"hiClearDate",  s:3, lbl:"more = sooner" },
  { f:"hiDebtInit",   t:"hiDebtBal",    s:3 },
  { f:"hiMinimums",   t:"hiDebtBal",    s:2 },
  { f:"hiClearDate",  t:"ioConvert",    s:3, lbl:"triggers same year" },
  { f:"hiClearDate",  t:"dispIncome",   s:3, lbl:"cap lifts" },
  { f:"hiClearDate",  t:"workFreeDate", s:2 },
  { f:"ioConvert",    t:"mortgagePnI",  s:3 },
  { f:"ioConvert",    t:"dispIncome",   s:2, lbl:"-$2,891/mo offset" },
  { f:"totalIncome",  t:"reqWork",      s:3 },
  { f:"totalCosts",   t:"reqWork",      s:3 },
  { f:"totalIncome",  t:"dispIncome",   s:3 },
  { f:"totalCosts",   t:"dispIncome",   s:3 },
  { f:"reApp",        t:"netWorth",     s:2 },
  { f:"hiDebtBal",    t:"netWorth",     s:2, lbl:"reduces NW" },
  { f:"investedCash", t:"netWorth",     s:2, lbl:"SB only" },
  { f:"dispIncome",   t:"workFreeDate", s:2 },
  { f:"workIncome",   t:"reqWork",      s:2, lbl:"tapers to zero" },
  { f:"brendaSs",     t:"workFreeDate", s:3, lbl:"Jan 2034 final push" },
  { f:"strRate",      t:"debtSweep",    s:1, lbl:"more income = more sweep" },
];
export const NODE_W=138, NODE_H=50;
export const COL_X=[68,220,378,542,706];
export const ROW_H=66, ROW_OFF=28;
export const SVG_W=870, SVG_H=640;
export function rNodePos(n){ return {x:COL_X[n.col], y:ROW_OFF+n.row*ROW_H}; }
